kind: pipeline
type: docker
name: Testing Python CI/CD

#steps:
#- name: Black Code Format Check
#  image: brandonrbedford/netauto
#  commands:
#  - black . --check

- name: Batfish Prechecks
  image: brandonrbedford/netauto
  commands:
    - python3 batfishcheck.py

- name: Check IP Interfaces
  image: brandonrbedford/netauto
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
  - python3 checkip.py