kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Install and deploy
  image: brandonrbedford/netauto
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
  - python3 checkip.py