kind: pipeline
type: docker
name: Testing Python CI/CD

services:
- name: batfish
  image: batfish/allinone
  ports:
	- 8888:8888
	- 9996:9996

steps:
- name: Black Code Format Check
  image: brandonrbedford/netauto
  commands:
  - black . --check

- name: Batfish Prechecks
  image: brandonrbedford/netauto
  commands:
    - python batfishcheck.py

- name: Check IP Interfaces
  image: brandonrbedford/netauto
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
  - python3 checkip.py